### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by JohnyDays** [stuartpb/rethinkdb-dockerfiles#11]
Pretty huge release from the rethinkdb team, would be nice to have a docker image for it so we can migrate

**Comment by stuartpb** [comment]
I'll handle this today after I've gotten some sleep.

**Comment by JohnyDays** [comment]
thanks a bunch! :rocket:

**Comment by benweet** [comment]
:+1:

**Comment by stuartpb** [comment]
Flerp, I opened a tab to cut releases for 2.1.0 and 2.1.1, and then I got distracted with a bunch of other things. I'll make a note in my status channel that I'm working on this now, so I remember to come back to it in case this happens again.

**Comment by stuartpb** [comment]
https://github.com/docker-library/official-images/pull/969

**Comment by JohnyDays** [comment]
Cool! it seems it's been merged. Closing this. Thanks!
