### ISSUE TITLE
Add release candidates

### ISSUE THREAD

**Issue by vierja** [stuartpb/rethinkdb-dockerfiles#3]
It would be cool to add release candidates support (and alpha/beta if it comes to that) I know it can be a lot more work to update but it's a good way to get people to try it before release.

**Comment by stuartpb** [comment]
If upstream packages them, sure.

**Comment by vierja** [comment]
How about something like:

```
FROM debian:jessie

MAINTAINER Stuart P. Bentley <stuart@testtrack4.com>

ENV RETHINKDB_PACKAGE_VERSION 2.0.0%2b0RC1~0jessie

ADD http://download.rethinkdb.com/dev/2.0.0-0RC1/rethinkdb_${RETHINKDB_PACKAGE_VERSION}_amd64.deb \ 
    /rethinkdb_${RETHINKDB_PACKAGE_VERSION}_amd64.deb

RUN apt-get update \
    && dpkg -i --force-depends /rethinkdb_${RETHINKDB_PACKAGE_VERSION}_amd64.deb \
    && apt-get -f -y install \
    && rm -rf /var/lib/apt/lists/*

VOLUME ["/data"]

WORKDIR /data

CMD ["rethinkdb", "--bind", "all"]

#   process cluster webui
EXPOSE 28015 29015 8080
```

I can create a PR if you want.

**Comment by stuartpb** [comment]
Considering that official library Dockerfiles should be reproducible, packages in http://download.rethinkdb.com/dev/ are ephemeral, [the 2.0.0 release is scheduled for next Monday](http://www.meetup.com/RethinkDB-SF-Meetup-Group/events/220927293/), and getting changes into the upstream Docker library usually has a 1-2 day turnaround from the initial PR, I think I'm going to hold off on 2.0.0 until the official release. In the future, I *might* do release candidates (if there are any again) on a dev branch in this repo, but I wouldn't expect upstream to list them (they'd have to be on stuartpb/rethinkdb).

**Comment by vierja** [comment]
Ok thanks!
