### ISSUE TITLE
rethinkdb warning

### ISSUE THREAD

**Issue by geddski** [stuartpb/rethinkdb-dockerfiles#4]
when using boot2docker on OSX rethinkdb gives this warning:

```
warn: Failed to sync parent directory of "/data/rethinkdb_data/metadata" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)
```

**Comment by geddski** [comment]
Found that this does not happen when you don't bind to the volume.

**Comment by stuartpb** [comment]
> (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)

So yeah, this is expected behavior. See https://github.com/boot2docker/boot2docker#folder-sharing for how to do volumes within boot2docker. (The command to start rethinkdb would then be `docker run --name some-rethink --volumes-from my-data -d rethinkdb`.)
