### ISSUE TITLE
2.0.3 release

### ISSUE THREAD

**Issue by techniq** [stuartpb/rethinkdb-dockerfiles#9]
[2.0.3](https://github.com/rethinkdb/rethinkdb/releases/tag/v2.0.3) is now out.  Care to push an update?

**Comment by stuartpb** [comment]
Just did.

**Comment by stuartpb** [comment]
Library PR: docker-library/official-images#814

**Comment by techniq** [comment]
Thanks

**Comment by stuartpb** [comment]
I'm actually considering writing a cronjob that can detect when a new version has been published and generate the commits automatically.

**Comment by techniq** [comment]
That would be nice :)
